### ISSUE TITLE
Remove versioneye.projectkey

### ISSUE THREAD

**Issue by johnjohndoe** [stempler/gradle-versioneye-plugin#10]
[I asked @VersionEye the other day](https://twitter.com/tbsprs/status/669499210773995520):

> Do I have to keep `versioneye.projectkey` and `versioneye.projectid` secret or can I commit it to version control?

[They replied as follows](https://twitter.com/VersionEye/status/669588410512855040):

> the project key is obsolete. It's only their for old clients. The projectID is enough for current clients.

You might want to remove `versioneye.projectkey` ...?

---

/cc @reiz

**Comment by stempler** [comment]
Thanks for the hint. I will take a look if this has any further implications and remove it if possible.

**Comment by reiz** [comment]
The projectKey was a more readable alternative for the projectID. But as it is anyway auto generated and stored in some properties file it doesn't makes much sense and is just redundant. I would like to get rid of it and clean the code base ;-)

**Comment by stempler** [comment]
Fixed and included in `1.1.0` release. The project key is obsolete and can be removed from `gradle.properties`.

**Comment by johnjohndoe** [comment]
:+1: I till try it out soon.

**Comment by johnjohndoe** [comment]
I updated to version 1.1.0 and run `./gradlew vEU`. This fails with the following error:

> java.lang.UnsupportedClassVersionError: org/standardout/gradle/plugin/versioneye/VersionEyePlugin : Unsupported major.minor version 52.0

**Comment by stempler** [comment]
This time built with Java 8 - I will try to add source and target compatibility settings for it to work with older Java versions (new issue #12). Did not think about that - the settings were not in place as it was no issue before.
