### ISSUE TITLE
Compatible binary for Java 6/7

### ISSUE THREAD

**Issue by stempler** [stempler/gradle-versioneye-plugin#12]
The latest release was compiled with/for Java 8 and is not usable with previous Java versions.

**Comment by stempler** [comment]
@johnjohndoe

Build was adapted to compile for Java 6 (bd22fc5439344e27848f3597f59e59440f6f3f01), release `1.1.1` includes the corresponding binaries.

May take a while before the plugin is available in the Gradle plugins repository (jcenter and mavenCentral should already work).

**Comment by johnjohndoe** [comment]
Works fine again. Thank you for the quick fix.
