### ISSUE TITLE
Support configuring custom base URL

### ISSUE THREAD

**Issue by sslavic** [stempler/gradle-versioneye-plugin#13]
Currently create and update tasks use hard-coded base URL which cannot be customized. This makes plugin usable only for public VersionEye server and unusable for VersionEye Enterprise installations.
Please consider making base URL configurable.

**Comment by stempler** [comment]
I've no experience with custom installations. Would making configurable what is currently the constant `https://www.versioneye.com` be sufficient or can it also be custom paths?

**Comment by sslavic** [comment]
Thanks for quick reply! Yes, it would be sufficient to make URL configurable.

**Comment by stempler** [comment]
I updated the current snapshot with this change. Can you test and verify if that works with a custom installation?

Version `1.2.0-SNAPSHOT` on Sonatype (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by sslavic** [comment]
Confirmed, it works. Thank you very much!

**Comment by stempler** [comment]
You're welcome :smile:
