### ISSUE TITLE
No option to read api_key from an environment variable

### ISSUE THREAD

**Issue by clayreimann** [stempler/gradle-versioneye-plugin#20]
The Maven plugin will read the api key from VERSIONEYE_API_KEY. This would be a nice feature to have for use in services like Travis-CI

**Comment by stempler** [comment]
Actually providing the API key via an environment variable should be possible right now, as there are a lot of different possibilities to set a Gradle property. Find a nice summary [here](http://mrhaki.blogspot.de/2010/09/gradle-goodness-different-ways-to-set.html) or take a look at the official [Gradle documentation](https://docs.gradle.org/current/userguide/build_environment.html) (see section *Gradle properties and system properties*).

Thus it should be possible to provide the API key via the environment variable `ORG_GRADLE_PROJECT_versioneye.api_key`. I admit, the variable name is not pretty, but it should do the trick.

**Comment by stempler** [comment]
Because environment variables with a dot are not easy to handle I added support for using the `VERSIONEYE_API_KEY` environment variable. It is used as fallback when the Gradle property is not set.

**Comment by clayreimann** [comment]
Thoughts on when you'll release this?
