### ISSUE TITLE
Results from multi-module projects are not aggregated

### ISSUE THREAD

**Issue by mmoayyed** [stempler/gradle-versioneye-plugin#24]
I am running the command: `gradle versionEyeUpdate` at the root of this project:
https://github.com/apereo/cas

I don't know how to quite aggregate results, because as the plugin is running and I refresh the versionEye reports web page, I see the results overwriting each other. Every module produces a different report, but versionEye is not aggregating them. 

Possible bug? misconfig?

**Comment by stempler** [comment]
Only works with the current snapshot (#22). See [here for the configuration](https://github.com/stempler/gradle-versioneye-plugin#multi-project-builds-since-14).

**Comment by mmoayyed** [comment]
Thanks. Just to clarify, that articular option only works in today's snapshot correct? 

If so, guess I am waiting then :) What's the timeline for the next release?

**Comment by stempler** [comment]
I'll do the release during this weekend. @johnjohndoe confirmed that it works, but you're welcome to test the [snapshot](https://github.com/stempler/gradle-versioneye-plugin#using-the-current-snapshot) yourself if you want.

**Comment by mmoayyed** [comment]
Ran a few quick tests, and so far I am not seeing any issues :) So release away! Thanks again.
