### ISSUE TITLE
Support for branch

### ISSUE THREAD

**Issue by dcoraboeuf** [stempler/gradle-versioneye-plugin#25]
In a complex project, there will several branches: features, fixes, maintenance, refactoring, etc.

I didn't see a way to set the branch in the {{versionUpdate}} task.

VersionEye supports this when interacting directly with GitHub, and that would be nice to be able to pass the branch parameter to the VersionEye plugin.

In my case, it happens that I know the branch I build so I can easily give it as a parameter to the `versionEye` extension.

**Comment by stempler** [comment]
After I first quick check I can't see a way how to do that.
The project is updated by uploading a file. The only other information provided is the project ID (see POST to `/v2/projects/{project_key}` in the [VersionEye API](https://www.versioneye.com/api/#!/projects/POST--version-projects--project_key---format-_post_3)).

The uploaded file is a `pom.json` file according to the definition [here](https://github.com/versioneye/pom_json_format). If there is a way to provide a branch there, it is not documented.
Or is this handled differently with Github? Is a project created for each branch?

@reiz Any ideas?

**Comment by reiz** [comment]
@dcoraboeuf @stempler In the VersionEye - GitHub integration each file on a different branch is a separate project. That makes sense and is used already by a couple thousand users & projects. With the Gradle plugin you can do it the same way. For each branch you create a new project and store the project ID(s) in the corresponding branch. After merging/deleting the branch the corresponding project can be removed from VersionEye as well.

**Comment by reiz** [comment]
@dcoraboeuf @stempler Another solution for this could be our pull request integration. See here: https://blog.versioneye.com/2016/08/16/pull-request-support-for-github/.
