### ISSUE TITLE
Provide an option to hide "xyz is up-to-date" messages

### ISSUE THREAD

**Issue by mmoayyed** [stempler/gradle-versioneye-plugin#26]
When I run the plugin, I see a lot of messages that indicate "some-dependency is up-to-date". I would like this message to become an optional feature, since I really just care about things that are not up-to-date. The rest mostly is just extra "noise" which makes it harder to track what dependency actually needs more attention. 

Thanks!

**Comment by stempler** [comment]
@msteiger You added the logging regarding the up-to-date states. What do you think makes sense as a default? Informing about up-to-date libraries or skipping them?

**Comment by msteiger** [comment]
It's probably a matter of personal taste. How about summarizing the up-to-date ones by default and adding a `-verbose` flag?

    abc can be updated to version 1.2.3
    xyz can be updated to version 3.4.5
    23 other dependencies are up to date

**Comment by mmoayyed** [comment]
That's fine with me. I only care about what is not up to date. So anything that compresses the rest of the log is fine.

**Comment by mmoayyed** [comment]
Any updates on this?

**Comment by msteiger** [comment]
I'm not using it actively, but it sounds like an interesting (small) project. I'll have a stab at it.

**Comment by stempler** [comment]
[Snapshot](https://github.com/stempler/gradle-versioneye-plugin#using-the-current-snapshot) is available for testing.
