### ISSUE TITLE
Error when running versioneye-create gradle task

### ISSUE THREAD

**Issue by reiz** [stempler/gradle-versioneye-plugin#30]
Hi @stempler. Somebody opened a ticket [here](https://bitbucket.org/versioneye/versioneye/issues/331/error-when-running-versioneye-create).

```
I am getting following error while running versioneye-create task for one of my java project.
FAILURE: Build failed with an exception.
What went wrong: Execution failed for task ':cattest-projects:calypso-cattest-extensions:versioneye-create'.

org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by stempler** [comment]
Sounds like it could be an issue with the Groovy version used by Gradle (e.g. if a Gradle version is used that uses an older Groovy version than the Groovy version the plugin was compiled with). Which Gradle version is used here?

**Comment by stempler** [comment]
See also this article: http://glaforge.appspot.com/article/groovy-2-3-5-out-with-upward-compatibility

So probably the solution is including the backports artifact in the buildscript dependencies or upgrading the Gradle version.

**Comment by reiz** [comment]
Hi @stempler Many Thanks for the quick response. I guess you are right. The user who reported this is anonymous, unfortunately. If he/she doesn't complain anymore I would recommend to close this by 1st January ;-)
