### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by heri333** [stempler/gradle-versioneye-plugin#37]
Support for configuring a HTTP proxy like for the Maven plugin seems to be missing. When the proxy is [configured for Gradle](https://docs.gradle.org/3.3/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy) the plugin fails to access www.versioneye.com.

**Comment by stempler** [comment]
The Groovy HTTP builder is used here and it seems it does use the Apache Http Client internally that does not pick up the settings from the default java system properties.

Here is an example of proxy configuration for the builder:
https://gist.github.com/bryanchug/4172603

**Comment by heri333** [comment]
Yes, but since the builder is created internally in the plugin, I cannot configure it. I'd propose adapting Util.createHttpBuilder() to check whether systemProp.http.* is set and configure the builder with those settings.

**Comment by stempler** [comment]
I did a pass on it but I don't really have time to test it in detail. So it would be great if you can test the [current snapshot](https://github.com/stempler/gradle-versioneye-plugin#using-the-current-snapshot) in respect to your problem.

**Comment by heri333** [comment]
I've tested it only without authentication, but that worked as expected :)

**Comment by stempler** [comment]
Basic proxy support contained in 1.5.0 release. We'll see if there are issues w/ authentication to the proxy - probably in case someone needs NTLM authentication.
