### ISSUE TITLE
The gradle-versioneye-plugin can't resolve our dynmic variables automatically from the root project

### ISSUE THREAD

**Issue by AhmedMehiny** [stempler/gradle-versioneye-plugin#38]
the gradle-versioneye-plugin can't resolve our dynmic variables automatically from the root project

as in $rootProject.googlePlayServices

`compile "com.google.firebase:firebase-core:$rootProject.googlePlayServices"`

we are using version 1.4

configuration in root project
`versioneye {
    includeSubProjects = true
    exclude configurations.findAll { !it.canBeResolved }*.name as String[]
  }`

<img width="665" alt="screen shot 2017-07-04 at 5 07 16 pm" src="https://user-images.githubusercontent.com/16867213/27835456-7e5a2e4c-60db-11e7-9e8e-bf2c3debf807.png">
<img width="644" alt="screen shot 2017-07-04 at 5 08 01 pm" src="https://user-images.githubusercontent.com/16867213/27835464-869434cc-60db-11e7-8aa1-4404f60bba44.png">

@reiz @stempler

**Comment by stempler** [comment]
What's the output of `gradle dependencies`?

**Comment by AhmedMehiny** [comment]
the version numbers
googlePlayServices = 10.2.6

**Comment by AhmedMehiny** [comment]
@stempler @reiz Do you guys have a solution for that?

**Comment by reiz** [comment]
Hi @stempler do you have an estimation for this? Is this difficult to solve?

**Comment by stempler** [comment]
From the output looks like this is the same problem a in #34.

Can you try again with the [current snapshot](https://github.com/stempler/gradle-versioneye-plugin#using-the-current-snapshot)?
The reason why it fails even if the workaround is used is most likely that subprojects are included and there are configurations that are not resolvable that don't occur in the main project.

**Comment by stempler** [comment]
Fix for issue with resolving configurations contained in 1.5.0 release. From the initial report it is not clear if this is the only problem here. Please reopen if the issue persists.
