### ISSUE TITLE
Option to ignore SSL certificate errors with VersionEye enterprise

### ISSUE THREAD

**Issue by snipem** [stempler/gradle-versioneye-plugin#40]
We have a custom signed SSL certificate which will randomly produce SSL exception such as:

```
Error:Execution failed for task ':versioneye-create'.
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Is there an option to ignore those errors? Like GIT_SSL_NO_VERIFY in Git.

**Comment by stempler** [comment]
There currently is no option for that. The Groovy HTTPBuilder that is used here under the hood uses the Apache Http Client. So I guess one would need to create a custom client with specific configuration for ignoring/trusting the certificate. See for instance this [Stackoverflow post](https://stackoverflow.com/questions/19517538/ignoring-ssl-certificate-in-apache-httpclient-4-3).

**Comment by snipem** [comment]
I was able to solve this problem by added the Custom Root CA to the Java keystore of the JDK being used for maven. Should be the same for Gradle. Thanks for your help.
