### ISSUE TITLE
gradle com.usaa.sonar-quality-gates plugin

### ISSUE THREAD

**Issue by shaktiMishra123** [stempler/gradle-versioneye-plugin#45]
* What went wrong:
Execution failed for task ':aggregation-api:applyQualityGate'.
> groovyx.net.http.HttpResponseException:

I am trying to implement sonarQube quality gates using gradle plugin com.usaa.sonar-quality-gates plugin but ended with above error.

Gradle Version : 5.6.4
sonarQube version : Version 6.7.6

**Comment by stempler** [comment]
Not sure how this relates - do you want to apply the plugin you mentioned to the build of this project?

**Comment by shaktiMishra123** [comment]
@stempler  thanks for your response.
To be precise i am trying to apply  com.usaa.sonar-quality-gates plugin in the build to check and fail the build in case it is not able to pass the quality profile mentioned in SonarQube.

I know we can do this with the jenkins plugin but we don't want to use jenkins plugin as our build will fail locally if there is dependency on jenkins in between. Hence we don't want to go with the mixed approach of jenkins and gradle. 

When i am trying to execute the task of this plugin in gradle by using below command i am getting the error i have listed in above post:
Command : 
gradlew :aggregation-api:applyQualityGate -Dsonar.host.url={sonarQube URL} -Dsonar.login={key to sonarQube} --stacktrace

**Comment by stempler** [comment]
So did you maybe intend to raise an issue here? https://github.com/usaa/sonar-quality-gates

**Comment by shaktiMishra123** [comment]
Thanks @stempler  i have raised the issue in the provided link
