### ISSUE TITLE
versionEyeUpdate fails with HttpResponseException

### ISSUE THREAD

**Issue by johnjohndoe** [stempler/gradle-versioneye-plugin#7]
I just run `./gradlew versionEyeUpdate` which fails with the following exception?

```
Execution failed for task ':app:versioneye-update'.
> groovyx.net.http.HttpResponseException: Gateway Time-out
```

Maybe, the API of VersionEye changed? /cc @reiz

**Comment by reiz** [comment]
@johnjohndoe Does this happen every time? Or was it a one hit wonder? The API didn't changed. Maybe the API was down for a while. That could be possible.

**Comment by johnjohndoe** [comment]
This time I received this error:

```
Execution failed for task ':app:versioneye-update'.
> groovyx.net.http.HttpResponseException: Internal Server Error
```

**Comment by johnjohndoe** [comment]
Steps to reproduce for an Android application project:

1. Delete `versioneye.projectkey` and `versioneye.projectid` from `app/gradle.properties`
2. Remove the associated project from *versioneye.com* if created previously
3. Run `./gradlew versionEyeCreate`
4. Run `./gradlew versionEyeUpdate`

**Comment by stempler** [comment]
I'm having the same problem with my VersionEye projects - but did not yet have the time to further check on it. I hope to do it on the weekend and see if I get a useful error message from the server.

**Comment by reiz** [comment]
@stempler Let me know if it is an issue with the API.

**Comment by stempler** [comment]
@reiz I tried it also via www.versioneye.com/api with the same result. The server gives no more information than it being an internal error.
Could it be an issue with the generated *pom.xml* that is being uploaded? Here a minified version that I used for the test:
```xml
<project>
  <name>hale-platform</name>
  <groupId></groupId>
  <version>3.0.0</version>
  <artifactId>hale-platform</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-opengis</artifactId>
      <version>8.0</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by reiz** [comment]
@stempler That looks fine so far. There was a bug on production that prevented the API accessing ElasticSearch and ohter backendend services. Can you please try again? Maybe it was related to that issue.

**Comment by reiz** [comment]
@stempler I just saved your xml content into a `pom.xml` file and uploaded it on the API page to create a new project and it worked. I got back a JSON document. I guess the problem in the past days was related to the configuration issue I mentioned in the prev. post. Please try again and confirm that it works for your.

**Comment by johnjohndoe** [comment]
Running `./gradlew versionEyeUpdate` worked for me just now. Thank you!

**Comment by stempler** [comment]
Works for me now again as well.
@reiz Thanks for the fix!
