### ISSUE TITLE
Bug: Content of gradle.properties is overwritten

### ISSUE THREAD

**Issue by johnjohndoe** [stempler/gradle-versioneye-plugin#8]
If the file `gradle.properties` already exists and contains content such as the following the task `versionEyeCreate` deletes the whole content and inserts its configuration.

```
# Some content I want to keep
# Do not delete this
```

I suggest you just **append** your configuration to leave the existing content untouched.

**Comment by stempler** [comment]
True, comments are not retained. I used the standard Java Properties API for simplicity, but this could be changed with small effort.

**Comment by johnjohndoe** [comment]
:smiley_cat:
